# Generated by Django 4.1.1 on 2022-09-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verifying_code',
            field=models.IntegerField(default=123456),
            preserve_default=False,
        ),
    ]
