# Generated by Django 4.1.1 on 2022-09-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_img_alter_profile_verifying_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verifying_code',
            field=models.CharField(max_length=245),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=245),
        ),
    ]
